/**
 * PDF Generator
 * Converts payslip data into a styled PDF buffer
 */

import type { PayslipData } from "./scraper";

export function generatePayslipHtml(data: PayslipData): string {
  const earningsRows = data.earnings
    .map(
      (e) => `
    <tr>
      <td class="desc">${e.description}</td>
      <td class="num">${e.hours || ""}</td>
      <td class="num">${e.amount}</td>
    </tr>`
    )
    .join("");

  const deductionRows = data.deductions
    .map(
      (d) => `
    <tr>
      <td class="desc">${d.description}</td>
      <td class="num">${d.amount}</td>
    </tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Payslip – ${data.period}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      font-size: 12px;
      color: #1a1a1a;
      background: #f9f9f9;
      padding: 32px;
    }
    .page {
      max-width: 720px;
      margin: 0 auto;
      background: #ffffff;
      border-radius: 8px;
      box-shadow: 0 2px 16px rgba(0,0,0,0.08);
      overflow: hidden;
    }
    .header {
      background: linear-gradient(135deg, #1a472a 0%, #2d6a4f 100%);
      color: white;
      padding: 24px 32px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .header h1 { font-size: 22px; font-weight: 700; letter-spacing: 0.5px; }
    .header .company { font-size: 11px; opacity: 0.8; margin-top: 4px; }
    .header .meta { text-align: right; font-size: 11px; opacity: 0.9; line-height: 1.6; }
    .period-bar {
      background: #e8f5e9;
      border-left: 4px solid #2d6a4f;
      padding: 10px 32px;
      font-size: 12px;
      color: #1a472a;
      font-weight: 600;
    }
    .body { padding: 24px 32px; }
    .tables-row {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 20px;
      margin-bottom: 20px;
    }
    .table-block h3 {
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 1px;
      color: #2d6a4f;
      border-bottom: 2px solid #2d6a4f;
      padding-bottom: 6px;
      margin-bottom: 8px;
    }
    table { width: 100%; border-collapse: collapse; }
    th {
      text-align: left;
      font-size: 10px;
      text-transform: uppercase;
      color: #666;
      letter-spacing: 0.5px;
      padding: 4px 6px;
      background: #f4f4f4;
    }
    td { padding: 5px 6px; border-bottom: 1px solid #f0f0f0; }
    td.num { text-align: right; font-variant-numeric: tabular-nums; }
    td.desc { color: #333; }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background: #f8fff8; }
    .totals {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 20px;
      margin-top: 12px;
    }
    .total-box {
      background: #f4f4f4;
      border-radius: 6px;
      padding: 12px 16px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .total-box.net {
      background: #1a472a;
      color: white;
      grid-column: 1 / -1;
    }
    .total-box .label { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; opacity: 0.8; }
    .total-box .value { font-size: 18px; font-weight: 700; }
    .footer {
      border-top: 1px solid #e8e8e8;
      padding: 12px 32px;
      display: flex;
      justify-content: space-between;
      font-size: 10px;
      color: #999;
    }
    .badge {
      display: inline-block;
      background: #e8f5e9;
      color: #2d6a4f;
      font-size: 10px;
      font-weight: 600;
      padding: 2px 8px;
      border-radius: 10px;
      margin-top: 4px;
    }
  </style>
</head>
<body>
  <div class="page">
    <div class="header">
      <div>
        <h1>CPI Outsourcing</h1>
        <div class="company">ClickPay Online Payroll System</div>
        <span class="badge">PAYSLIP</span>
      </div>
      <div class="meta">
        <div>Generated: ${new Date().toLocaleDateString("en-PH", { dateStyle: "long" })}</div>
        <div style="margin-top:4px; opacity:0.7; font-size:10px;">Auto-generated by Payslip Automator</div>
      </div>
    </div>

    <div class="period-bar">
      Pay Period: ${data.period || "Current Period"}
    </div>

    <div class="body">
      <div class="tables-row">
        <div class="table-block">
          <h3>Earnings</h3>
          <table>
            <thead>
              <tr>
                <th>Description</th>
                <th style="text-align:right">Hrs</th>
                <th style="text-align:right">Amount</th>
              </tr>
            </thead>
            <tbody>
              ${earningsRows || '<tr><td colspan="3" style="color:#999; text-align:center; padding:12px;">No earnings data</td></tr>'}
            </tbody>
          </table>
        </div>

        <div class="table-block">
          <h3>Deductions</h3>
          <table>
            <thead>
              <tr>
                <th>Description</th>
                <th style="text-align:right">Amount</th>
              </tr>
            </thead>
            <tbody>
              ${deductionRows || '<tr><td colspan="2" style="color:#999; text-align:center; padding:12px;">No deductions</td></tr>'}
            </tbody>
          </table>
        </div>
      </div>

      <div class="totals">
        <div class="total-box">
          <span class="label">Total Earnings</span>
          <span class="value">₱ ${data.totalEarnings || "—"}</span>
        </div>
        <div class="total-box">
          <span class="label">Total Deductions</span>
          <span class="value">₱ ${data.totalDeductions || "—"}</span>
        </div>
        <div class="total-box net">
          <span class="label" style="opacity:0.7">Net Pay</span>
          <span class="value">₱ ${data.netPay || "—"}</span>
        </div>
      </div>
    </div>

    <div class="footer">
      <span>This is a system-generated payslip. No signature required.</span>
      <span>Scraped: ${new Date(data.scrapedAt).toLocaleString("en-PH")}</span>
    </div>
  </div>
</body>
</html>`;
}

export async function generatePdfBuffer(html: string): Promise<Buffer> {
  try {
    // Try using puppeteer for PDF generation (more reliable)
    let browser;
    
    if (process.env.NODE_ENV === "production" || process.env.USE_CHROMIUM === "true") {
      const chromium = await import("@sparticuz/chromium");
      const puppeteer = await import("puppeteer-core");
      browser = await puppeteer.default.launch({
        args: chromium.default.args,
        defaultViewport: chromium.default.defaultViewport,
        executablePath: await chromium.default.executablePath(),
        headless: true,
      });
    } else {
      const puppeteer = await import("puppeteer");
      browser = await puppeteer.default.launch({
        headless: true,
        args: ["--no-sandbox", "--disable-setuid-sandbox"],
      });
    }

    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });
    
    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "0mm", bottom: "0mm", left: "0mm", right: "0mm" },
    });
    
    await browser.close();
    return Buffer.from(pdfBuffer);
  } catch (error) {
    console.error("[PDF] Puppeteer PDF failed, trying html-pdf-node:", error);
    
    // Fallback to html-pdf-node
    const htmlPdf = await import("html-pdf-node");
    const file = { content: html };
    const options = { format: "A4", printBackground: true };
    
    return new Promise((resolve, reject) => {
      htmlPdf.default.generatePdf(file, options, (err: Error | null, buffer: Buffer) => {
        if (err) reject(err);
        else resolve(buffer);
      });
    });
  }
}
